# Generated by Django 3.0.6 on 2020-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('username', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=400)),
                ('polarity', models.FloatField()),
            ],
        ),
    ]
